// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAol32dpXZHQ9OGuv9LKRpVwxUsEr-0cpI',
    appId: '1:770508154172:web:128ab1a25164843f172a39',
    messagingSenderId: '770508154172',
    projectId: 'todoappfirestore-79243',
    authDomain: 'todoappfirestore-79243.firebaseapp.com',
    storageBucket: 'todoappfirestore-79243.appspot.com',
    measurementId: 'G-JXDZ5H508X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7mFyCtlDn-clr-c19nUtca_O_O4caDg',
    appId: '1:770508154172:android:5704234ab61ad4a9172a39',
    messagingSenderId: '770508154172',
    projectId: 'todoappfirestore-79243',
    storageBucket: 'todoappfirestore-79243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSejvDNBMwqiDdk9ZdOcTEBf1KqSGa5dQ',
    appId: '1:770508154172:ios:f8071fa253a901c0172a39',
    messagingSenderId: '770508154172',
    projectId: 'todoappfirestore-79243',
    storageBucket: 'todoappfirestore-79243.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSejvDNBMwqiDdk9ZdOcTEBf1KqSGa5dQ',
    appId: '1:770508154172:ios:f8071fa253a901c0172a39',
    messagingSenderId: '770508154172',
    projectId: 'todoappfirestore-79243',
    storageBucket: 'todoappfirestore-79243.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAol32dpXZHQ9OGuv9LKRpVwxUsEr-0cpI',
    appId: '1:770508154172:web:e30e6efc46946d0b172a39',
    messagingSenderId: '770508154172',
    projectId: 'todoappfirestore-79243',
    authDomain: 'todoappfirestore-79243.firebaseapp.com',
    storageBucket: 'todoappfirestore-79243.appspot.com',
    measurementId: 'G-JFFH0ZM6C8',
  );

}